{% set name = "pytorch-msssim" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytorch_msssim-{{ version }}.tar.gz
  sha256: 53273f03ce5c435f706f49feb5110a8afe90b2519484b0fe0df9639670106d0b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.0
    - pip
  run:
    - python >=3.0
    - pytorch

test:
  imports:
    - pytorch_msssim
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/VainF/pytorch-msssim
  summary: Fast and differentiable MS-SSIM and SSIM for pytorch.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jaeakle
